version: "3.3"
#networks:
#  synapsenet:
#    driver: bridge
#    ipam:
#      config:
#      - subnet: 172.25.0.0/24
services:
    synapse:
        image: "matrixdotorg/synapse:latest"
        restart: always
        container_name: "synapse"
#        network_mode: synapsenet
        volumes:
            - "/mnt/2TB/synapse/data:/data"
        environment:
            VIRTUAL_HOST: "matrix.pogmom.me"
            VIRTUAL_PORT: 8008
            SYNAPSE_SERVER_NAME: "matrix.pogmom.me"
            SYNAPSE_REPORT_STATS: "yes"
        ports:
            - "8008:8008/tcp"
            - "8448:8448/tcp"

    riot-web:
        ports:
            - '86:80'
        image: bubuntux/riot-web
        restart: always

    postgresql:
        image: postgres:latest
        restart: always
        hostname: synapse-postgresql-1
        #network_mode: synapsenet
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: synapse
            POSTGRES_DB: synapse
            POSTGRES_INITDB_ARGS: "--encoding='UTF8' --lc-collate='C' --lc-ctype='C'"
        volumes:
            - "/mnt/2TB/synapse/postgres:/var/lib/postgresql/"
        ports:
            - "5432:5432/tcp"
