version: "3.8"

networks:
  docker-local:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${NETWORKING_SUBNET_PREFIX}0/24

services:

  ddns-updater: # dns updater, prevents issues caused by cycling residential ip address https://hub.docker.com/r/qmcgaw/ddns-updater
    image: qmcgaw/ddns-updater:latest
    container_name: ddns-updater
#    networks:
#      docker-local:
#        ipv4_address: ${SUBNET_PREFIX}2
    environment:
      - LISTENING_PORT=8000
      - ROOT_URL=/
      - TZ=${TZ}
    volumes:
      - ${DATA_PATH}/ddns-updater/data:/updater/data
    ports:
      - ${DDNS_PORT}:8000/tcp
    restart: unless-stopped

  nginx-proxy-manager: # web ui for managing nginx reverse proxy config https://nginxproxymanager.com/
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    networks:
      docker-local:
        ipv4_address: ${NETWORKING_SUBNET_PREFIX}5
    volumes:
      - ${DATA_PATH}/nginx-proxy-manager/data:/data
      - ${DATA_PATH}/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
      - ${DATA_PATH}/nginx-proxy-manager/static:/static
      - ${DATA_PATH}/nginx-proxy-manager/snippets:/snippets:ro
    ports:
      - ${NGINX_HTTP_PORT}:80
      - ${NGINX_WEBUI_PORT}:81
      - ${NGINX_HTTPS_PORT}:443
    restart: unless-stopped
