version: "3.8"

services:

  rebble-asr-pogmom:
    image: rebble-asr-pogmom
    container_name: rebble-asr-pogmom
    ports:
      - "732:443"
    environment:
      - SPEECH_API_KEY=${REBBLE_SPEECH_KEY}
    restart: always

  rebble-weather-pogmom:
    image: rebble-weather-pogmom
    container_name: rebble-weather-pogmom
    ports:
      - "733:5000"
    environment:
      - IBM_API_KEY=${REBBLE_WEATHER_KEY}
      - FLASK_APP=weather
    restart: always
