version: "3.8"

services:

  home-assistant: #home automation hub. Control lights, audio, temperature, etc. https://www.home-assistant.io/installation/linux#docker>
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: home-assistant
    volumes:
      - ${DATA_PATH}/home-assistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
      - ${MEDIA_PATH}:/media/Media:ro
      - ${DATA_PATH}/home-assistant/persistent:/media/persistent
    privileged: true
    network_mode: host
    restart: unless-stopped

  wyoming-piper: # text to speech for home assistant https://github.com/rhasspy/wyoming-addons
    image: rhasspy/wyoming-piper
    container_name: wyoming-piper
    volumes:
      - ${DATA_PATH}/wyoming_piper/data:/data
    ports:
      - ${WYOMING_PIPER_PORT}:10200
    command: --voice en-us-libritts-high
    restart: unless-stopped

  wyoming-whisper: #speech to text for home assistant https://github.com/rhasspy/wyoming-addons
    image: rhasspy/wyoming-whisper
    container_name: wyoming_whisper
    volumes:
      - ${DATA_PATH}/wyoming_whisper/data:/data
    ports:
      - ${WYOMING_WHISPER_PORT}:10300
    command: --model tiny-int8 --language en
    restart: unless-stopped
