version: "3"
services:
  minecraft-server:
    image: itzg/minecraft-server
    container_name: mc-smp
    ports:
      - 25565:25565/tcp
      - 25565:25565/udp
      - 19132:19132/tcp
      - 19132:19132/udp
    environment:
      EULA: "TRUE"
      EXEC_DIRECTLY: "TRUE"
      MEMORY: "4G"
      VERSION: "LATEST"
      TYPE: "PAPER"
#      FORCE_REDOWNLOAD: "TRUE"
#      SPIGOT_DOWNLOAD_URL: "https://github.com/pogmommy/mcpage/releases/download/v.120/spigot-1.20.jar"
      SPIGET_RESOURCES: "18494"
      MODS_FILE: "/extras/mods.txt"
      #WORLD: /worlds/SMP.2022
#      EXTRA_ARGS: "--world-dir ./worlds/"
      DIFFICULTY: "hard"
      MOTD: "§3Join the discord at §ddis.pogmom.me§f\\n§fSurvival Server§f || §4Qu§cee§6r L§eib§aer§2at§1io§9n N§5ow§d!"
      OPS: "pogmommy"
      ICON: "/extras/server-icon.png"
      MAX_PLAYERS: "50"
      ALLOW_NETHER: "TRUE"
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "TRUE"
      GENERATE_STRUCTURES: "TRUE"
      MODE: "survival"
      SERVER_NAME: "Pogmommy"
      ENABLE_ROLLING_LOGS: "TRUE"
      TZ: ${TZ}
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - "/mnt/2TB/minecraft/smp:/data"
#      - "./plugins:/plugins"
#      - "./worlds:/worlds"
      - "./extras:/extras"
